import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Content from "../../components/Content";
import { styled, ThemeProvider, createTheme } from "@mui/material/styles";
// const inter = Inter({ subsets: ['latin'] })

const mainTheme = createTheme({
  palette: {
    primary: {
      main: "#9763f6",
    },
    secondary: {
      main: "#f73378",
    },
    // Background colors
    info: {
      main: "#121212",
      light: "#191b21",
    },
  },
});

const Root = styled("div")(({ theme }) => ({
  marginTop: "160px",
  paddingBottom: "160px",
  backgroundColor: "black",
}));

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Score</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://i.postimg.cc/44wF0BLr/images-removebg-preview.png"
        />
      </Head>
      <ThemeProvider theme={mainTheme}>
        <Root>
          <Content />
        </Root>
      </ThemeProvider>
    </>
  );
}
